language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'

install:
    - pip install flake8 bandit black
    - pip install .
    - npm install -g markdownlint-cli@0.23.2

script:
    - make test
    - scraper -h
