query ($numRepos: Int!, $pgCursor: String) {
  viewer {
    starredRepositories(first: $numRepos, after: $pgCursor) {
      nodes {
        nameWithOwner
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
# {"numRepos": 3, "pgCursor": null }